### ISSUE TITLE
Area below footer is not black

### ISSUE THREAD

**Issue by april** [mozilla/ssl-config-generator#17]
It would be nice if the area below the footer were black. But how??

**Comment by jrchamp** [comment]
I took this question literally and tested it with salmon first to make sure I wasn't wrong.
```css
html {
    background-color: black;
}
```
Please note that this does affect the `margin-top` at the top of the page, so you may want to set `body {}` to have white.
